const express = require('express');
const constoller = require('../controller/crud');
const route = express.Router();
const authenticateJWT = require('../middleware/web-auth');
route.get('/login', constoller.showLogin);
route.post('/login', constoller.loginUser);
route.get('/register', constoller.showRegister);
route.post('/register', constoller.registerUser);
route.get('/', authenticateJWT, constoller.index);
route.get('/logout', authenticateJWT, constoller.logout);
route.get('/all-users', authenticateJWT, constoller.allUser);  
route.get('/add-user', authenticateJWT, constoller.addUserForm);
route.post('/save-user', authenticateJWT, constoller.saveUser);
route.get('/edit-user/:id', authenticateJWT, constoller.editUserForm);
route.post('/update-user', authenticateJWT, constoller.updateUser);
route.get('/user-delete/:id', authenticateJWT, constoller.deleteUser);
route.get('/cases', authenticateJWT, constoller.getCase);
module.exports = route;  